### ISSUE TITLE
Foreign key constraints from foreign schema incorrect.

### ISSUE THREAD

**Issue by PranavSathy** [adrianandrei-ca/staruml-postgresql#1]
The generated PSQL for a table that has a foreign key constraint to a table in another schema always results in the foreign key constraint referring to "public" schema. For example:

Table auth.user has a foreign key constraint to core.organization, the generated PSQL code always adds a foreign key constraint from auth.user to public.organization.

**Comment by adrianandrei-ca** [comment]
Thanks for your PR
