### ISSUE TITLE
Not marked as installed

### ISSUE THREAD

**Issue by tormes** [adrianandrei-ca/staruml-postgresql#11]
After installing this extension in StarUML last version (2.8.1), in "Tools", "Extension Manager", the small  button at right labeled "Install" does not change to "Installed" and grayed. Other extensions work as expected.
But the extension was in-fact installed. If we press then button "Install" again it prompts to "Overwrite" the previous one. And the extension appears in the second tab, which shows the list of installed extensions.

**Comment by muriloazevedo** [comment]
Here, I click to install and just keep "loading", but none was installed.

**Comment by adrianandrei-ca** [comment]
I do not think I can control this from the extension.
