### ISSUE TITLE
Put constraints at end of generated SQL

### ISSUE THREAD

**Issue by data-ux** [adrianandrei-ca/staruml-postgresql#7]
Currently the extension generates the foreign key constraints for a table right after the table definition. This is a problem because the referenced table might not exist yet. When trying to load the generated SQL to Postgres, there will be an error.

All constraints should be applied at the end of the SQL file, after all tables have been created.

**Comment by adrianandrei-ca** [comment]
This is fixed, checked in but not released yet.
