### ISSUE TITLE
incorrect schema for foreign key referenced table

### ISSUE THREAD

**Issue by vukbgit** [adrianandrei-ca/staruml-postgresql#8]
Hi:

- table_A is into schema Schema1 (defined by 'schema' tag) 
- table_A has primary key set on column Id
- table B contains a foreign key which references table_A.Id
- into DDL constraint definition reference is to **public.table_A** instead of **Schema1.table_A**

I patched SGenerator.js around line 343 changing:
`var refSchemaName = self.schemaName(refTableObj._parent._parent, options);`
to
`var refSchemaName = self.schemaName(refTableObj._parent, options);`
and now schema is correctly determined.

I'm sorry if this is not the right way to tell you but:

- I'm not very confident with github forking/pulling/branching/etc process
- I modified code in other parts (forcing default for UUID fields to public.uuid_generate_v4() in a quick and dirty way) so it's not suited for publishing
- I could not find other way to communicate with you
Thanks & keep up the good work

**Comment by adrianandrei-ca** [comment]
I founded and fixed this issue in master branch but not putting out the
next release didn't help.

I should do that sooner rather than later.

Thank you for using the product.
